[package]
name = "streami"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
axum = { version = "0.8.0-alpha.1", features = ["multipart"] }
http = "1.2.0"
tower-http = { version = "0.6.2", features = ["cors"] }
tokio = { version = "1.42.0", features = ["rt-multi-thread", "fs"] }
sanitize-filename = "0.5"
futures = "0.3.31"
tokio-util = { version = "0.7.13", features = ["io"] }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"